/**
 * @fileoverview gRPC-Web generated client stub for file_upload
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v3.21.12
// source: file_upload.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.file_upload = require('./file_upload_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.file_upload.FileUploadGrpcEndpointClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.file_upload.FileUploadGrpcEndpointPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.file_upload.UploadImageRequest,
 *   !proto.file_upload.UploadImageResponse>}
 */
const methodDescriptor_FileUploadGrpcEndpoint_UploadImageAsync = new grpc.web.MethodDescriptor(
  '/file_upload.FileUploadGrpcEndpoint/UploadImageAsync',
  grpc.web.MethodType.UNARY,
  proto.file_upload.UploadImageRequest,
  proto.file_upload.UploadImageResponse,
  /**
   * @param {!proto.file_upload.UploadImageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.file_upload.UploadImageResponse.deserializeBinary
);


/**
 * @param {!proto.file_upload.UploadImageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.file_upload.UploadImageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.file_upload.UploadImageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.file_upload.FileUploadGrpcEndpointClient.prototype.uploadImageAsync =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/file_upload.FileUploadGrpcEndpoint/UploadImageAsync',
      request,
      metadata || {},
      methodDescriptor_FileUploadGrpcEndpoint_UploadImageAsync,
      callback);
};


/**
 * @param {!proto.file_upload.UploadImageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.file_upload.UploadImageResponse>}
 *     Promise that resolves to the response
 */
proto.file_upload.FileUploadGrpcEndpointPromiseClient.prototype.uploadImageAsync =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/file_upload.FileUploadGrpcEndpoint/UploadImageAsync',
      request,
      metadata || {},
      methodDescriptor_FileUploadGrpcEndpoint_UploadImageAsync);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.file_upload.DownloadImageRequest,
 *   !proto.file_upload.DownloadImageResponse>}
 */
const methodDescriptor_FileUploadGrpcEndpoint_DownloadImageAsync = new grpc.web.MethodDescriptor(
  '/file_upload.FileUploadGrpcEndpoint/DownloadImageAsync',
  grpc.web.MethodType.UNARY,
  proto.file_upload.DownloadImageRequest,
  proto.file_upload.DownloadImageResponse,
  /**
   * @param {!proto.file_upload.DownloadImageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.file_upload.DownloadImageResponse.deserializeBinary
);


/**
 * @param {!proto.file_upload.DownloadImageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.file_upload.DownloadImageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.file_upload.DownloadImageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.file_upload.FileUploadGrpcEndpointClient.prototype.downloadImageAsync =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/file_upload.FileUploadGrpcEndpoint/DownloadImageAsync',
      request,
      metadata || {},
      methodDescriptor_FileUploadGrpcEndpoint_DownloadImageAsync,
      callback);
};


/**
 * @param {!proto.file_upload.DownloadImageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.file_upload.DownloadImageResponse>}
 *     Promise that resolves to the response
 */
proto.file_upload.FileUploadGrpcEndpointPromiseClient.prototype.downloadImageAsync =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/file_upload.FileUploadGrpcEndpoint/DownloadImageAsync',
      request,
      metadata || {},
      methodDescriptor_FileUploadGrpcEndpoint_DownloadImageAsync);
};


module.exports = proto.file_upload;

