/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: file_upload.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as file_upload_pb from './file_upload_pb';


export class FileUploadGrpcServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorUploadAsync = new grpcWeb.MethodDescriptor(
    '/FileUploadGrpcService/UploadAsync',
    grpcWeb.MethodType.UNARY,
    file_upload_pb.FileUploadRequest,
    file_upload_pb.FileUploadResponse,
    (request: file_upload_pb.FileUploadRequest) => {
      return request.serializeBinary();
    },
    file_upload_pb.FileUploadResponse.deserializeBinary
  );

  uploadAsync(
    request: file_upload_pb.FileUploadRequest,
    metadata: grpcWeb.Metadata | null): Promise<file_upload_pb.FileUploadResponse>;

  uploadAsync(
    request: file_upload_pb.FileUploadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: file_upload_pb.FileUploadResponse) => void): grpcWeb.ClientReadableStream<file_upload_pb.FileUploadResponse>;

  uploadAsync(
    request: file_upload_pb.FileUploadRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: file_upload_pb.FileUploadResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/FileUploadGrpcService/UploadAsync',
        request,
        metadata || {},
        this.methodDescriptorUploadAsync,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/FileUploadGrpcService/UploadAsync',
    request,
    metadata || {},
    this.methodDescriptorUploadAsync);
  }

}

