/**
 * @fileoverview gRPC-Web generated client stub for file_upload
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: file_upload.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as file_upload_pb from './file_upload_pb';


export class FileUploadGrpcEndpointClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorUploadImageAsync = new grpcWeb.MethodDescriptor(
    '/file_upload.FileUploadGrpcEndpoint/UploadImageAsync',
    grpcWeb.MethodType.UNARY,
    file_upload_pb.UploadImageRequest,
    file_upload_pb.UploadImageResponse,
    (request: file_upload_pb.UploadImageRequest) => {
      return request.serializeBinary();
    },
    file_upload_pb.UploadImageResponse.deserializeBinary
  );

  uploadImageAsync(
    request: file_upload_pb.UploadImageRequest,
    metadata: grpcWeb.Metadata | null): Promise<file_upload_pb.UploadImageResponse>;

  uploadImageAsync(
    request: file_upload_pb.UploadImageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: file_upload_pb.UploadImageResponse) => void): grpcWeb.ClientReadableStream<file_upload_pb.UploadImageResponse>;

  uploadImageAsync(
    request: file_upload_pb.UploadImageRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: file_upload_pb.UploadImageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/file_upload.FileUploadGrpcEndpoint/UploadImageAsync',
        request,
        metadata || {},
        this.methodDescriptorUploadImageAsync,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/file_upload.FileUploadGrpcEndpoint/UploadImageAsync',
    request,
    metadata || {},
    this.methodDescriptorUploadImageAsync);
  }

  methodDescriptorDownloadImageAsync = new grpcWeb.MethodDescriptor(
    '/file_upload.FileUploadGrpcEndpoint/DownloadImageAsync',
    grpcWeb.MethodType.UNARY,
    file_upload_pb.DownloadImageRequest,
    file_upload_pb.DownloadImageResponse,
    (request: file_upload_pb.DownloadImageRequest) => {
      return request.serializeBinary();
    },
    file_upload_pb.DownloadImageResponse.deserializeBinary
  );

  downloadImageAsync(
    request: file_upload_pb.DownloadImageRequest,
    metadata: grpcWeb.Metadata | null): Promise<file_upload_pb.DownloadImageResponse>;

  downloadImageAsync(
    request: file_upload_pb.DownloadImageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: file_upload_pb.DownloadImageResponse) => void): grpcWeb.ClientReadableStream<file_upload_pb.DownloadImageResponse>;

  downloadImageAsync(
    request: file_upload_pb.DownloadImageRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: file_upload_pb.DownloadImageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/file_upload.FileUploadGrpcEndpoint/DownloadImageAsync',
        request,
        metadata || {},
        this.methodDescriptorDownloadImageAsync,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/file_upload.FileUploadGrpcEndpoint/DownloadImageAsync',
    request,
    metadata || {},
    this.methodDescriptorDownloadImageAsync);
  }

}

